### ISSUE TITLE
Muy bien hecho, Anna

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-annabranco#1]
Tu ejercicio es bueno hasta decir basta, de hecho creo que te puedes haber divertido haciéndolo, lo cual me parece genial :)
A mejorar... supongo que el aspecto gráfico me podría poner puntilloso, pero sería eso "ser puntillitas"... has hecho un trabajo un poco más allá del deber.

Muy buen trabajo!

Si quieres puedo proponerte alguna mejor para avanzarlo más, pero ya si quieres.

![Well done!](https://media.giphy.com/media/bKBM7H63PIykM/giphy.gif)

**Comment by annabranco** [comment]
El aspecto gráfico me parece un poco "Win95", pero he intentado seguir el modelo. :P

He avanzado un poco más en ello hoy usando el localStorage que me has comentado.
Pero si tienes cualquier otra sugerencia para avanzarlo más, me encantaría hacerlo.
He aprendido muchísimo con ese ejercicio. ^^
